name: secure_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_storage: ^0.0.1
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.5
  http: ^1.5.0
  image_picker: ^1.2.0
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
